service: SlsCloudFlarePluginTest

provider:
  name: aws


plugins:
  modules:
    - ./index.js

custom:
  cloudflare:
    disabled: true
    domain: "" # from env
    auth:
      # option 1
      email: "" # from env
      token: "" # from env

      # option 2
      apiToken: ""

    record:
      name: ""
      content: ""
      #content: "#{cf:CloudFrontDomain}"

